//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDFrAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_VAR
    {
        public int CONFIG_VAR_ID { get; set; }
        public int Vlan { get; set; }
        public string Man_IP { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordSSH { get; set; }
        public string Terminal { get; set; }
    
        public virtual CONFIG CONFIG { get; set; }
    }
}
