
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DDFrAS
{

using System;
    using System.Collections.Generic;
    
public partial class CONFIG_VAR
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CONFIG_VAR()
    {

        this.CONFIGs = new HashSet<CONFIG>();

    }


    public int CONFIG_VAR_ID { get; set; }

    public int Vlan { get; set; }

    public string Man_IP { get; set; }

    public string Username { get; set; }

    public string PasswordSSH { get; set; }

    public string Terminal { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CONFIG> CONFIGs { get; set; }

}

}
