//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDFrAS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DDFrASEntities : DbContext
    {
        public DDFrASEntities()
            : base("name=DDFrASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONFIG> CONFIGs { get; set; }
        public virtual DbSet<CONFIG_VAR> CONFIG_VAR { get; set; }
        public virtual DbSet<POP> POPs { get; set; }
        public virtual DbSet<PORT> PORTs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<SSH_COMMANDOS> SSH_COMMANDOS { get; set; }
        public virtual DbSet<SSH_COMMANDS> SSH_COMMANDS { get; set; }
        public virtual DbSet<SWITCH> SWITCHes { get; set; }
    }
}
