//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDFrAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORT
    {
        public int Port_ID { get; set; }
        public string Port_Name { get; set; }
    
        public virtual CONFIG CONFIG { get; set; }
        public virtual SWITCH SWITCH { get; set; }
    }
}
