//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDFrAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSH_COMMANDOS
    {
        public int Commando_ID { get; set; }
        public string Commando_Name { get; set; }
        public string Commando_Temp { get; set; }
    }
}
